package kp;

import java.util.List;

/**
 * The US cities.
 */
public class Cities {
    /**
     * The list.
     */
    static List<String> list = List.of(
            "New York City",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Dallas-Fort Worth",
            "Miami",
            "Atlanta",
            "Philadelphia",
            "Washington DC",
            "Phoenix",
            "Boston",
            "Seattle",
            "Detroit",
            "San Diego",
            "San Francisco",
            "Minneapolis",
            "Tampa",
            "Denver",
            "Las Vegas",
            "Riverside-San Bernardino",
            "San Antonio",
            "Baltimore",
            "Charlotte",
            "Austin",
            "Portland",
            "Sacramento",
            "St. Louis",
            "Orlando",
            "Indianapolis",
            "San Jose",
            "Cincinnati",
            "Cleveland",
            "Kansas City",
            "Columbus",
            "Pittsburgh",
            "Raleigh",
            "Virginia Beach",
            "Milwaukee",
            "Jacksonville",
            "Nashville",
            "Salt Lake City",
            "Providence",
            "Memphis",
            "Richmond",
            "Louisville",
            "McAllen",
            "Oklahoma City",
            "Hartford",
            "Tucson",
            "New Orleans",
            "El Paso",
            "Temecula-Murrieta",
            "Albuquerque",
            "Bridgeport-Stamford",
            "Cape Coral",
            "Honolulu",
            "Buffalo",
            "Birmingham",
            "Omaha",
            "Provo-Orem",
            "Fresno",
            "Tulsa",
            "Knoxville",
            "Allentown",
            "Baton Rouge",
            "Columbia SC",
            "Sarasota-Bradenton",
            "Ogden-Layton",
            "Charleston-North Charleston",
            "Rochester",
            "Dayton",
            "Bakersfield",
            "Concord",
            "The Woodlands",
            "Colorado Springs",
            "Springfield",
            "Mission Viejo",
            "Albany",
            "Grand Rapids",
            "Victorville-Hesperia-Apple Valley",
            "New Haven",
            "Kissimmee",
            "Fayetteville-Springdale",
            "Des Moines",
            "Harrisburg",
            "Greenville",
            "Akron",
            "Worcester",
            "Port St. Lucie",
            "Winston-Salem",
            "Wichita",
            "Little Rock",
            "Palm Bay-Melbourne",
            "Reno",
            "Lancaster-Palmdale",
            "Poughkeepsie-Newburgh",
            "Lancaster",
            "Daytona Beach-Port Orange",
            "Toledo",
            "Madison"
    );
}
